---
- hosts: dbservers
  tasks:
    - name: Server uptime
      bash: uptime
    # - name: Server disk usage
    #   bash: du -h
    - name: Server memory usage
      bash: free -m

- hosts: webservers
  tasks:
    - name: Server uptime
      bash: uptime
    # - name: Server disk usage
    #   bash: du -h
    - name: Say hello
      bash: echo "Hello ${hostname}"