---
- hosts: dbservers
  tasks:
    - name: Server uptime
      bash: uptime
    - name: Server memory usage
      bash: free -m

- hosts: webservers
  tasks:
    - name: Server uptime
      bash: uptime
    - name: Say hello
      bash: echo "Hello World"

- hosts: loadbalancers
  tasks:
    - name: Install nginx
      bash: apt-get update && apt-get install nginx -y